// Generated by CoffeeScript 1.6.2
/*
// ==UserScript==
// @id             ajax_pixiv_bookmark_(changed)
// @name           AJAX Pixiv Bookmark (changed)
// @version        2.0.3
// @namespace      http://blog.k2ds.net/
// @author         killtw
// @description    Using AJAX to add a bookmark in Pixiv
// @match          http://www.pixiv.net/member_illust.php?*
// @match          http://www.pixiv.net/setting_user.php
// @grant        none
// ==/UserScript==
*/
var addjQuery, main;

addjQuery = function(callback) {
	var e;

	e = document.createElement('script');
	e.setAttribute('src', 'http://ajax.googleapis.com/ajax/libs/jquery/1.10.1/jquery.min.js');
	e.addEventListener('load', function() {
		var script;

		script = document.createElement('script');
		script.textContent = "(" + callback.toString() + ")();";
		document.body.appendChild(script);
	});
	document.body.appendChild(e);
};

main = function() {
	var settings;

	settings = {
		default_tag: localStorage.default_tag
	};
	$('table tbody:eq(1)').append('\
  <tr><th>預設標籤</th><td>\
  <p>當沒有符合的標籤時將使用代入預設標籤，空白即不代入預設標籤</p>\
  <p><input type="text" name="default_tag" onkeyup="localStorage.setItem(\'default_tag\', this.value)" value="' + settings.default_tag + '"></p>\
  </td></tr>');
  
  	var restricted = false;
	$('div.bookmark-container a._button.add-bookmark').click(function(e) {
		var illust_id, illust_tags, input_tag, tt;

		e.preventDefault();
		illust_tags = [];
		input_tag = [];
		illust_id = document.URL.match(/\d+/)[0];
		tt = $('input[name="tt"]').val();

		// get tags of illustration
		var tag, _i, _len, _ref;

		if (document.URL.match('manga')) {
			$.ajax({
				url: "http://www.pixiv.net/member_illust.php?mode=medium&illust_id=" + illust_id,
				type: 'GET',
				dataType: 'html',
				async: false,
				success: function(data) {
					var tag, _i, _len, _ref;

					_ref = $(data).find('a.text');
					for (_i = 0, _len = _ref.length; _i < _len; _i++) {
						tag = _ref[_i];
						illust_tags.push(tag.text);
						// if R-18 || R-18G -> restricted
						if (tag.text == "R-18" || tag.text == "R-18G") {
							restricted = true;
						}
					}
					return tt = $(data).find('input[name="tt"]')[0].value;
				}
			});
		} else {
			_ref = $('a.text');
			for (_i = 0, _len = _ref.length; _i < _len; _i++) {
				tag = _ref[_i];
				illust_tags.push(tag.text);
				// if R-18 || R-18G -> restricted
				if (tag.text == "R-18" || tag.text == "R-18G") {
					restricted = true;
				}
			}
		}

		// search best-matching tags for the illustration
		// (abandoned)
		/*
		  var tag, _i, _len, _ref;

		  _ref = $(data).find('a.tag-name');
		  for (_i = 0, _len = _ref.length; _i < _len; _i++) {
		    tag = _ref[_i];
		    if (illust_tags.indexOf(tag.text) !== -1) {
		      input_tag.push(tag.text);
		    }
		  }
		  if (input_tag.length === 0) {
		    input_tag.push(settings.default_tag);
		  }
		*/

		$.ajax({
			url: 'bookmark_add.php',
			data: {
				mode: 'add',
				tt: tt,
				id: illust_id,
				//            tag: input_tag.join(' '),
				tag: illust_tags.join(' '),
				type: 'illust',
				form_sid: '',
				restrict: (restricted ? '1' : '0')
			},
			dataType: 'html',
			type: 'POST',
			beforeSend: function() {
				$("div.bookmark-container a._button.add-bookmark").text('追加中…');
			},
			success: function() {
				$("div.bookmark-container a._button.add-bookmark")
					.text('加入成功')
					.delay(1000)
					.fadeOut('fast')
					.removeClass('add-bookmark')
					.removeClass('_button')
					.unbind()
					.addClass('button-on')
					.attr('href', 'bookmark_add.php?type=illust&illust_id=' + illust_id)
					.text('編輯收藏')
					.fadeIn('fast');
			}
		});
	});
};

addjQuery(main);
